recurring_events_registration.registrant.config:
  type: config_object
  label: 'Recurring Events Registration Config'
  mapping:
    show_capacity:
      type: boolean
      label: 'Whether to display the remaining capacity for an event during registration'
    insert_redirect_choice:
      type: string
      label: 'Choose where registrant form redirects'
    insert_redirect_other:
      type: string
      label: 'Type custom URL here'
    use_admin_theme:
      type: boolean
      label: 'Use the administration theme when managing registrations'
    limit:
      type: integer
      label: 'The items per page to show on registrant listing'
    date_format:
      type: string
      label: 'The formatting of dates when displaying registrants'
    title:
      type: string
      label: 'The title of the registrants'
    email_notifications:
      type: boolean
      label: 'Whether to enable email notifications'
    email_notifications_queue:
      type: boolean
      label: 'Whether to use the email notifications queue'
    successfully_registered:
      type: label
      label: 'The message to display when a registrant is successfully created'
    successfully_registered_waitlist:
      type: label
      label: 'The message to display when a registrant is successfully added to the waitlist'
    successfully_updated:
      type: label
      label: 'The message to display when a registrant is successfully updated'
    successfully_updated_waitlist:
      type: label
      label: 'The message to display when a registrant on the waitlist is successfully updated'
    already_registered:
      type: label
      label: 'The message to display when a user is already registered for an event'
    registration_closed:
      type: label
      label: 'The message to display when registration is closed for an event'
    notifications:
      type: sequence
      sequence:
        type: mapping
        label: 'Email notification'
        mapping:
          enabled:
            type: boolean
            label: 'Whether to enable these notifications'
          subject:
            type: label
            label: 'The email subject for these notifications'
          body:
            type: text
            label: 'The email body for these notifications'
field.widget.settings.event_registration:
  type: mapping
  label: 'Recurring Events Show Enable Waitlist'
  mapping:
    show_enable_waitlist:
      type: boolean
      label: 'Enable Waiting List'
