recurring_events_registration.registrant_type.*:
  type: config_entity
  label: 'registrant type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    description:
      type: string
      label: 'Description'
    uuid:
      type: string
    notifications:
      type: sequence
      label: 'Notification settings'
      sequence:
        type: mapping
        mapping:
          overridden:
            type: boolean
            label: 'Whether the notification settings are overridden for this registrant type.'
          enabled:
            type: boolean
            label: 'Whether the notification is enabled.'
          subject:
            type: string
            label: 'The subject of the notification.'
          body:
            type: string
            label: 'The body of the notification.'
